Added more infomation on Index-Mathing Materials for purchase.
OpenGammaProject/Open-Gamma-Detector pull request #33
Opened 2023-04-21 02:39 UTC by sebyon

I added a small table in the hardware section with some Index-Matching Material to choose from. Added a comment addressing the MICROFC-60035-SMT-TR and MICROFC-60035-SMT-TR1 difference (tape and reel purchase volume) explaining the price difference. 

Added some notes in the MD for future updates.

2023-04-21 10:49 UTC, Phoenix1747 reviewed
Nice, thanks for your contributions!

2023-04-21 10:49 UTC, Phoenix1747 commented on hardware/README.md
> +* MICROFC-60035-SMT-TR1 (the exact same as above, however will be more expensive to purchase as sold in smaller batches to suppliers)
Can you explain this to me? Both on Mouser and Digikey you can buy individual SiPMs and they come in the same packaging in my experience.

2023-04-21 10:49 UTC, Phoenix1747 commented on hardware/README.md
> +<!--- I'll look at adding some reliable sources down the track for new ones - Sebyon --->
Some recommendations:

- https://www.ost-photonics.com/
- https://www.epic-crystal.com/

Both are Chinese manufacturers, but seem to provide good quality crystals and are pretty cheap too. Epic Crystal's scintillators are also sold by Gammaspectacular.

2023-04-21 13:49 UTC, sebyon commented on hardware/README.md
> +* MICROFC-60035-SMT-TR1 (the exact same as above, however will be more expensive to purchase as sold in smaller batches to suppliers)
So with the TR, there is the MOQ from the supplier for 5000 units (the whole reel I assume), while the TR1 is jst the tape from the manufacturer. Likely the TR1 was purchased before the TR, or Mouser / Digikey just automatically bought both and just recuperate cost based on some back-end default profit margin based on the initial order. 

Can see this with the datasheet on page 15. 
[MICROC_SERIES_D-2315622.pdf](https://github.com/OpenGammaProject/Open-Gamma-Detector/files/11296267/MICROC_SERIES_D-2315622.pdf)

2023-04-21 13:52 UTC, sebyon commented on hardware/README.md
> +<!--- I'll look at adding some reliable sources down the track for new ones - Sebyon --->
I think these are the two major Chinese new crystals that don't cost an arm and a leg from my knowledge.

2023-04-21 14:10 UTC, Phoenix1747 requested changes
Typos, other than that LGTM.

2023-04-21 14:10 UTC, Phoenix1747 commented on hardware/README.md
> +|[Index Matching Gel, 3 cc](https://www.thorlabs.com/thorproduct.cfm?partnumber=G608N3)|Thorlabs| 1.43 | 1,060,000 | $47.46 | High viscosity, works welll for fibre optic coupling. |
typo "works welll"

2023-04-21 14:10 UTC, Phoenix1747 commented on hardware/README.md
> +<!--- I'll look at adding some reliable sources down the track for new ones - Sebyon --->
Yup, I've had pretty good experiences with OST Photonics so far. I think they're also the cheapest actually. Do you want to add something to this section right now or do you want to wait and do some more research?

2023-04-22 04:31 UTC, sebyon commented on hardware/README.md
> +|[Index Matching Gel, 3 cc](https://www.thorlabs.com/thorproduct.cfm?partnumber=G608N3)|Thorlabs| 1.43 | 1,060,000 | $47.46 | High viscosity, works welll for fibre optic coupling. |
I'll fix this in next pull request.

2023-04-22 04:31 UTC, sebyon commented on hardware/README.md
> +|[Index-Matching Fluid](https://www.newport.com/f/index-matching-fluid) | Newport | 1.52 | 100 | $45.60 | Low viscosity may made setting the SiPM and crystal window difficult. However, the RI is the
Fixed this typo in next pull.

2023-04-22 10:11 UTC, Phoenix1747 approved these changes
Great, thanks! 👍🏻

2023-04-22 10:11 UTC, merged